AllCops:
  Includes:
    - Gemfile
    - Rakefile
  Excludes:
    - spec/fixtures/**

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
StringLiterals:
  Enabled: false
